---
#
# Ansible managed
#
repository:
  description: Ansible role to install OS updates.
  homepage: https://mullholland.net
  topics: development, system, security, updates, ansible, molecule, tox, playbook
