---
- name: Install OS Updates on RedHat
  ansible.builtin.include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Rocky"

- name: Install OS Updates on Debian
  ansible.builtin.include_tasks: Debian.yml
  when: ansible_os_family == "Debian"
